### ISSUE TITLE
Unable to save Pins with URL image to newly created Board

### ISSUE THREAD

**Issue by phillipkregg** [brownabs/react-pin#17]
Hey Abbey!  Great talking with you today.

The Pinterest app looks nice, but I noticed a bug that I wanted to bring to your attention.  

Steps to reacreate below, Have a good one!

###################################

Steps to recreate:

1. Create a Board

![image](https://user-images.githubusercontent.com/1066044/107079554-a03c9b00-67b5-11eb-8f2a-3f4a4ca0deec.png)

2. Click "View Pins"

![image](https://user-images.githubusercontent.com/1066044/107079610-b6e2f200-67b5-11eb-86ab-cc37ef268422.png)

3. Click "Create Pin" and enter form information (notice image is a URL - not uploaded)

![image](https://user-images.githubusercontent.com/1066044/107079731-e2fe7300-67b5-11eb-944d-2ac3034969f4.png)

4. Click "Save" - nothing happens but this error is generated:

![image](https://user-images.githubusercontent.com/1066044/107079834-06292280-67b6-11eb-8919-907db1da1d7c.png)

**Comment by brownabs** [comment]
@phillipkregg Thank you for bringing this to my attention. Working on issue ticket now.

**Comment by brownabs** [comment]
CreatePin() in Pins.js component state was not passed correctly to PinForm component and boardId was defined correctly.
